export const projectObjOne = {
  id: "triviapp",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "React, Redux, Material UI",
  headline: "Triviapp",
  description: "Play a game of Trivia with your friends",
  buttonLabel: "Live Demo",
  imgStart: false,
  img: require("../../images/svg-1.svg"),
  alt: "triviapp preview",
  dark: false,
  primary: false,
  darkText: true,
}

export const projectObjTwo = {
  id: "futfriends",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "React, Redux, Material UI",
  headline: "FutFriends",
  description: "Look up popular upcoming matches and create watchparty with your friends",
  buttonLabel: "Live Demo",
  imgStart: true,
  img: require("../../images/svg-1.svg"),
  alt: "FutFriends preview",
  dark: true,
  primary: true,
  darkText: false,
}

export const projectObjThree = {
  id: "protask",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "business services",
  headline: "Solutions that meet your needs",
  description:
    "We create custom and responsive web applications to saves you time when it comes to managing you business",
  buttonLabel: "Live Demo",
  imgStart: false,
  img: require("../../images/svg-1.svg"),
  alt: "protask preview",
  dark: false,
  primary: false,
  darkText: true,
}

export const projectObjFour = {
  id: "netflix",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "React, Material UI",
  headline: "Browse Netflix",
  description: "Browse the entire Netflix Library",
  buttonLabel: "Live Demo",
  imgStart: true,
  img: require("../../images/svg-1.svg"),
  alt: "browse netflix preview",
  dark: true,
  primary: true,
  darkText: false,
}
